Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 163
Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 163
Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 431
Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 431
Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 406
Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 117
Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 117
Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 117
Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 98
Internal Server Error: /api/me/
Traceback (most recent call last):
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\api\views.py", line 150, in user_profile
    "language": prefs.language if prefs else "en",
AttributeError: 'UserPreference' object has no attribute 'language'
"GET /api/me/ HTTP/1.1" 500 145
Internal Server Error: /api/me/
Traceback (most recent call last):
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\api\views.py", line 150, in user_profile
    "language": prefs.language if prefs else "en",
AttributeError: 'UserPreference' object has no attribute 'language'
"GET /api/me/ HTTP/1.1" 500 145
Internal Server Error: /api/me/
Traceback (most recent call last):
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\api\views.py", line 150, in user_profile
    "language": prefs.language if prefs else "en",
AttributeError: 'UserPreference' object has no attribute 'language'
"GET /api/me/ HTTP/1.1" 500 145
Internal Server Error: /api/me/
Traceback (most recent call last):
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\api\views.py", line 150, in user_profile
    "language": prefs.language if prefs else "en",
AttributeError: 'UserPreference' object has no attribute 'language'
"GET /api/me/ HTTP/1.1" 500 145
Internal Server Error: /api/me/
Traceback (most recent call last):
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\api\views.py", line 150, in user_profile
    "language": prefs.language if prefs else "en",
AttributeError: 'UserPreference' object has no attribute 'language'
"GET /api/me/ HTTP/1.1" 500 145
Internal Server Error: /api/me/
Traceback (most recent call last):
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\api\views.py", line 150, in user_profile
    "language": prefs.language if prefs else "en",
AttributeError: 'UserPreference' object has no attribute 'language'
"GET /api/me/ HTTP/1.1" 500 145
Internal Server Error: /api/me/
Traceback (most recent call last):
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\91730\Documents\GenTA\Library_AI\api\views.py", line 150, in user_profile
    "language": prefs.language if prefs else "en",
AttributeError: 'UserPreference' object has no attribute 'language'
"GET /api/me/ HTTP/1.1" 500 145
Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 163
Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 163
Internal Server Error: /api/recommend/
"POST /api/recommend/ HTTP/1.1" 500 163
